import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import toast from 'react-hot-toast';
export function PaymentInfoSheet({ user, contributionAmount, onClose }) {
    function copyToClipboard(value, label) {
        navigator.clipboard.writeText(value);
        toast.success(`${label} number copied.`);
    }
    return (_jsx("div", { className: "modal-overlay", onClick: onClose, children: _jsxs("div", { className: "modal-sheet", onClick: (e) => e.stopPropagation(), children: [_jsx("div", { className: "modal-handle" }), _jsx("h2", { style: { fontSize: 18, marginBottom: 6 }, children: "Send Payment To" }), _jsxs("p", { style: { fontSize: 14, color: 'var(--text2)', marginBottom: 20 }, children: ["Send \u20B1", contributionAmount.toLocaleString(), " to the organizer then wait for confirmation."] }), _jsxs("div", { style: { display: 'flex', flexDirection: 'column', gap: 10 }, children: [_jsxs("div", { className: "payment-method", children: [_jsx("div", { className: "payment-icon gcash-icon", children: "GC" }), _jsxs("div", { style: { flex: 1 }, children: [_jsx("p", { style: { fontWeight: 700, fontSize: 14 }, children: "GCash" }), _jsx("p", { style: { fontSize: 13, color: 'var(--text2)' }, children: user.userId })] }), _jsx("button", { className: "btn btn-outline", style: { width: 'auto', padding: '8px 12px', fontSize: 13 }, onClick: () => copyToClipboard(user.userId, 'GCash'), children: "Copy" })] }), _jsxs("div", { className: "payment-method", children: [_jsx("div", { className: "payment-icon maya-icon", children: "MY" }), _jsxs("div", { style: { flex: 1 }, children: [_jsx("p", { style: { fontWeight: 700, fontSize: 14 }, children: "Maya" }), _jsx("p", { style: { fontSize: 13, color: 'var(--text2)' }, children: user.userId })] }), _jsx("button", { className: "btn btn-outline", style: { width: 'auto', padding: '8px 12px', fontSize: 13 }, onClick: () => copyToClipboard(user.userId, 'Maya'), children: "Copy" })] })] }), _jsx("div", { style: { marginTop: 20 }, children: _jsx("button", { className: "btn btn-outline", onClick: onClose, children: "Close" }) })] }) }));
}
