import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import toast from 'react-hot-toast';
import { QrCodeDisplay } from './QrCodeDisplay';
import { EmptyState } from '../../../components/EmptyState';
export function PaymentInfoSheet({ organizerGCash, organizerMaya, contributionAmount, onClose, }) {
    const [qrTab, setQrTab] = useState('static');
    function copyToClipboard(value, label) {
        navigator.clipboard.writeText(value);
        toast.success(`${label} number copied.`);
    }
    function buildDynamicPayload(number) {
        return `amount=${contributionAmount.toFixed(2)}|recipient=${number}`;
    }
    return (_jsx("div", { className: "modal-overlay", onClick: onClose, children: _jsxs("div", { className: "modal-sheet", onClick: (e) => e.stopPropagation(), children: [_jsx("div", { className: "modal-handle" }), _jsx("h2", { style: { fontSize: 18, marginBottom: 6 }, children: "Send Payment To" }), _jsxs("p", { style: { fontSize: 14, color: 'var(--text2)', marginBottom: 20 }, children: ["Send \u20B1", contributionAmount.toLocaleString(), " to the organizer then wait for confirmation."] }), _jsx("div", { className: "tab-group", style: { marginBottom: 20 }, children: ['static', 'dynamic'].map((tab) => (_jsx("button", { className: `tab-pill ${qrTab === tab ? 'active' : ''}`, onClick: () => setQrTab(tab), children: tab === 'static' ? 'Static QR' : 'Dynamic QR' }, tab))) }), _jsxs("div", { style: { display: 'flex', flexDirection: 'column', gap: 20 }, children: [_jsxs("div", { children: [_jsxs("div", { style: { display: 'flex', alignItems: 'center', gap: 8, marginBottom: 12 }, children: [_jsx("div", { className: "payment-icon gcash-icon", style: { width: 28, height: 28, fontSize: 10 }, children: "GC" }), _jsx("p", { style: { fontWeight: 700, fontSize: 14 }, children: "GCash" })] }), organizerGCash ? (_jsxs("div", { style: { display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12 }, children: [_jsx(QrCodeDisplay, { value: qrTab === 'static' ? organizerGCash : buildDynamicPayload(organizerGCash), label: organizerGCash }), _jsx("button", { className: "btn btn-outline", style: { padding: '8px 16px', fontSize: 13 }, onClick: () => copyToClipboard(organizerGCash, 'GCash'), children: "Copy Number" })] })) : (_jsx(EmptyState, { message: "No GCash number on file." }))] }), _jsx("div", { className: "divider" }), _jsxs("div", { children: [_jsxs("div", { style: { display: 'flex', alignItems: 'center', gap: 8, marginBottom: 12 }, children: [_jsx("div", { className: "payment-icon maya-icon", style: { width: 28, height: 28, fontSize: 10 }, children: "MY" }), _jsx("p", { style: { fontWeight: 700, fontSize: 14 }, children: "Maya" })] }), organizerMaya ? (_jsxs("div", { style: { display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12 }, children: [_jsx(QrCodeDisplay, { value: qrTab === 'static' ? organizerMaya : buildDynamicPayload(organizerMaya), label: organizerMaya }), _jsx("button", { className: "btn btn-outline", style: { padding: '8px 16px', fontSize: 13 }, onClick: () => copyToClipboard(organizerMaya, 'Maya'), children: "Copy Number" })] })) : (_jsx(EmptyState, { message: "No Maya number on file." }))] })] }), _jsx("div", { style: { marginTop: 24 }, children: _jsx("button", { className: "btn btn-outline", onClick: onClose, children: "Close" }) })] }) }));
}
