import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Spinner } from '../../../components/Spinner';
function EyeIcon({ open }) {
    return open ? (_jsxs("svg", { xmlns: "http://www.w3.org/2000/svg", width: "18", height: "18", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", children: [_jsx("path", { d: "M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z" }), _jsx("circle", { cx: "12", cy: "12", r: "3" })] })) : (_jsxs("svg", { xmlns: "http://www.w3.org/2000/svg", width: "18", height: "18", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", children: [_jsx("path", { d: "M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19m-6.72-1.07a3 3 0 1 1-4.24-4.24" }), _jsx("line", { x1: "1", y1: "1", x2: "23", y2: "23" })] }));
}
export function LoginForm({ values, errors, loading, onChange, onSubmit, onRegisterClick }) {
    const [showPassword, setShowPassword] = useState(false);
    return (_jsxs("div", { style: { minHeight: '100vh', display: 'flex', flexDirection: 'column', justifyContent: 'center', padding: '0 28px' }, children: [_jsxs("div", { style: { marginBottom: 40 }, children: [_jsx("div", { style: {
                            width: 56, height: 56, borderRadius: 16,
                            background: 'linear-gradient(135deg, var(--primary), var(--accent))',
                            display: 'flex', alignItems: 'center', justifyContent: 'center',
                            marginBottom: 24, fontSize: 26,
                        }, children: "\uD83D\uDCB0" }), _jsxs("h1", { style: { fontSize: 30, fontWeight: 700 }, children: ["Ipon", _jsx("span", { style: { color: 'var(--primary)' }, children: "Mo" })] }), _jsx("p", { style: { color: 'var(--text2)', marginTop: 8, fontSize: 15 }, children: "Paluwagan made simple. Sign in to continue." })] }), _jsxs("div", { className: "input-group", children: [_jsx("label", { children: "Email" }), _jsx("input", { type: "email", name: "email", placeholder: "you@email.com", value: values.email, onChange: onChange, onKeyDown: (e) => e.key === 'Enter' && onSubmit(), style: errors.email ? { borderColor: 'var(--danger)' } : undefined }), errors.email && (_jsx("p", { style: { color: 'var(--danger)', fontSize: 12, marginTop: 5, fontWeight: 500 }, children: errors.email }))] }), _jsxs("div", { className: "input-group", children: [_jsx("label", { children: "Password" }), _jsxs("div", { style: { position: 'relative' }, children: [_jsx("input", { type: showPassword ? 'text' : 'password', name: "password", placeholder: "\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022", value: values.password, onChange: onChange, onKeyDown: (e) => e.key === 'Enter' && onSubmit(), style: { paddingRight: 48, ...(errors.password ? { borderColor: 'var(--danger)' } : {}) } }), _jsx("button", { type: "button", onClick: () => setShowPassword((v) => !v), style: {
                                    position: 'absolute', right: 14, top: '50%', transform: 'translateY(-50%)',
                                    background: 'none', border: 'none', cursor: 'pointer',
                                    color: 'var(--text3)', display: 'flex', alignItems: 'center', padding: 0,
                                }, "aria-label": showPassword ? 'Hide password' : 'Show password', children: _jsx(EyeIcon, { open: showPassword }) })] }), errors.password && (_jsx("p", { style: { color: 'var(--danger)', fontSize: 12, marginTop: 5, fontWeight: 500 }, children: errors.password }))] }), _jsx("div", { style: { marginTop: 8 }, children: _jsxs("button", { className: "btn btn-primary", onClick: onSubmit, disabled: loading, children: [loading && _jsx(Spinner, {}), loading ? 'Signing in...' : 'Sign In'] }) }), _jsxs("p", { style: { textAlign: 'center', marginTop: 24, fontSize: 14, color: 'var(--text3)' }, children: ["No account yet?", ' ', _jsx("span", { style: { color: 'var(--primary)', fontWeight: 700, cursor: 'pointer' }, onClick: onRegisterClick, children: "Sign up" })] })] }));
}
